import React, { useState, useRef, useEffect } from 'react';
import {
  Send,
  Bot,
  User,
  TrendingUp,
  PieChart,
  Target,
  DollarSign,
  Download,
  Save,
  Sparkles
} from 'lucide-react';
import axios from 'axios';
import { useAuth } from '../context/AuthContext';
import LoadingSpinner from '../components/common/LoadingSpinner';
import FinancialChart from '../components/charts/FinancialChart';

const Advisor = () => {
  const { user } = useAuth();
  const [messages, setMessages] = useState([]);
  const [inputMessage, setInputMessage] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [currentVisualization, setCurrentVisualization] = useState(null);
  const messagesEndRef = useRef(null);
  const inputRef = useRef(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => scrollToBottom(), [messages]);

  useEffect(() => {
    // Add welcome message
    const welcomeMessage = {
      id: '1',
      type: 'bot',
      content: `Hi ${user?.name?.split(' ')[0] || 'there'}! 👋 I'm your AI financial advisor. I can help you with budgeting, saving strategies, investment advice, and more. What would you like to discuss today?`,
      timestamp: new Date(),
      suggestions: [
        'How can I save more money?',
        'Analyze my spending patterns',
        'Help me optimize my goals',
        'Investment recommendations'
      ]
    };
    setMessages([welcomeMessage]);
    console.log('Added welcome message:', welcomeMessage);
  }, [user]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!inputMessage.trim() || isLoading) return;

    const userMessage = {
      id: Date.now().toString(),
      type: 'user',
      content: inputMessage,
      timestamp: new Date()
    };
    setMessages(prev => [...prev, userMessage]);
    console.log('User sent message:', userMessage);

    setInputMessage('');
    setIsLoading(true);

    try {
      const response = await axios.post('/api/advisor/chat', {
        message: inputMessage,
        context: {
          userId: user?.id,
          previousMessages: messages.slice(-5)
        }
      });
      console.log('AI response received:', response.data);

      const botMessage = {
        id: (Date.now() + 1).toString(),
        type: 'bot',
        content: response.data.response || 'No response from AI',
        timestamp: new Date(),
        insights: Array.isArray(response.data.insights) ? response.data.insights : [],
        suggestions: Array.isArray(response.data.suggestions) ? response.data.suggestions : [],
        visualization: response.data.visualization || null,
        followUpQuestions: Array.isArray(response.data.followUpQuestions) ? response.data.followUpQuestions : []
      };

      setMessages(prev => [...prev, botMessage]);
      if (botMessage.visualization) setCurrentVisualization(botMessage.visualization);

    } catch (error) {
      console.error('Chat error:', error);

      // Fallback to mock response
      const mockResponse = generateMockResponse(inputMessage, user);
      console.log('Using mock response:', mockResponse);

      const botMessage = {
        id: (Date.now() + 1).toString(),
        type: 'bot',
        content: mockResponse.content,
        timestamp: new Date(),
        insights: Array.isArray(mockResponse.insights) ? mockResponse.insights : [],
        suggestions: Array.isArray(mockResponse.suggestions) ? mockResponse.suggestions : [],
        visualization: mockResponse.visualization || null,
        followUpQuestions: Array.isArray(mockResponse.followUpQuestions) ? mockResponse.followUpQuestions : []
      };

      setMessages(prev => [...prev, botMessage]);
      if (botMessage.visualization) setCurrentVisualization(botMessage.visualization);
    } finally {
      setIsLoading(false);
    }
  };

  const handleSuggestionClick = (suggestion) => {
    console.log('Suggestion clicked:', suggestion);
    setInputMessage(suggestion);
    inputRef.current?.focus();
  };

  const saveVisualization = async () => {
    if (!currentVisualization) return;

    try {
      await axios.post('/api/visualizations', {
        title: currentVisualization.title || 'Financial Visualization',
        type: currentVisualization.type,
        data: currentVisualization.data,
        description: 'Generated by AI Advisor'
      });
      console.log('Visualization saved:', currentVisualization);
      alert('Visualization saved successfully!');
    } catch (error) {
      console.error('Failed to save visualization:', error);
      alert('Failed to save visualization');
    }
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <div className="mb-8 flex items-center space-x-3 mb-2">
          <div className="w-10 h-10 bg-gradient-to-r from-purple-500 to-indigo-600 rounded-xl flex items-center justify-center">
            <Bot className="w-6 h-6 text-white" />
          </div>
          <div>
            <h1 className="text-3xl font-bold text-gray-900">AI Financial Advisor</h1>
            <p className="text-gray-600">Get personalized financial advice powered by AI</p>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Chat Section */}
          <div className="lg:col-span-2">
            <div className="card h-[600px] flex flex-col">
              <div className="flex-1 overflow-y-auto p-4 space-y-4">
                {messages.map((message) => (
                  <MessageBubble
                    key={message.id}
                    message={message}
                    onSuggestionClick={handleSuggestionClick}
                  />
                ))}

                {isLoading && (
                  <div className="flex items-center space-x-2 text-gray-500">
                    <Bot className="w-5 h-5" />
                    <LoadingSpinner size="small" />
                    <span className="text-sm">AI is thinking...</span>
                  </div>
                )}

                <div ref={messagesEndRef} />
              </div>

              {/* Input */}
              <div className="border-t border-gray-200 p-4">
                <form onSubmit={handleSubmit} className="flex space-x-2">
                  <input
                    ref={inputRef}
                    type="text"
                    value={inputMessage}
                    onChange={(e) => setInputMessage(e.target.value)}
                    placeholder="Ask me anything about your finances..."
                    className="flex-1 input-field"
                    disabled={isLoading}
                  />
                  <button
                    type="submit"
                    disabled={isLoading || !inputMessage.trim()}
                    className="btn-primary px-4 disabled:opacity-50"
                  >
                    <Send className="w-4 h-4" />
                  </button>
                </form>

                {/* Quick Actions */}
                <div className="flex flex-wrap gap-2 mt-3">
                  {quickActions.map((action, index) => (
                    <button
                      key={index}
                      onClick={() => handleSuggestionClick(action.text)}
                      className="inline-flex items-center px-3 py-1 text-xs bg-gray-100 hover:bg-gray-200 rounded-full text-gray-700 transition-colors"
                    >
                      <action.icon className="w-3 h-3 mr-1" />
                      {action.text}
                    </button>
                  ))}
                </div>
              </div>
            </div>
          </div>

          {/* Visualization & Tools */}
          <div className="space-y-6">
            {currentVisualization && (
              <div className="card">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="text-lg font-semibold text-gray-900">Visualization</h3>
                  <div className="flex space-x-2">
                    <button
                      onClick={saveVisualization}
                      className="p-2 text-gray-600 hover:text-primary-600 rounded"
                    >
                      <Save className="w-4 h-4" />
                    </button>
                    <button className="p-2 text-gray-600 hover:text-primary-600 rounded">
                      <Download className="w-4 h-4" />
                    </button>
                  </div>
                </div>
                <VisualizationDisplay visualization={currentVisualization} />
              </div>
            )}

            {/* AI Insights */}
            <div className="card">
              <div className="flex items-center space-x-2 mb-4">
                <Sparkles className="w-5 h-5 text-purple-600" />
                <h3 className="text-lg font-semibold text-gray-900">Recent Insights</h3>
              </div>
              <div className="space-y-3">
                {messages
                  .filter(m => m.type === 'bot' && Array.isArray(m.insights))
                  .slice(-3)
                  .map((message, index) => (
                    <div key={index} className="p-3 bg-purple-50 rounded-lg">
                      {message.insights.map((insight, idx) => (
                        <p key={idx} className="text-sm text-purple-800">• {insight}</p>
                      ))}
                    </div>
                  ))}
              </div>
            </div>

            {/* Financial Health Score */}
            <div className="card">
              <h3 className="text-lg font-semibold text-gray-900 mb-4">Financial Health Score</h3>
              <div className="text-center">
                <div className="text-3xl font-bold text-green-600 mb-2">
                  {user?.financialProfile?.healthScore || 75}
                </div>
                <p className="text-sm text-gray-600 mb-4">Good financial health</p>
                <div className="space-y-2 text-left">
                  <ScoreItem label="Savings Rate" score={80} />
                  <ScoreItem label="Debt Management" score={70} />
                  <ScoreItem label="Budget Adherence" score={75} />
                  <ScoreItem label="Investment Diversity" score={65} />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

// ----------------- MessageBubble -----------------
const MessageBubble = ({ message = {}, onSuggestionClick = () => {} }) => {
  const isBot = message.type === 'bot';
  const content = message.content || '';
  const insights = Array.isArray(message.insights) ? message.insights : [];
  const suggestions = Array.isArray(message.suggestions) ? message.suggestions : [];
  const followUpQuestions = Array.isArray(message.followUpQuestions) ? message.followUpQuestions : [];

  return (
    <div className={`flex ${isBot ? 'justify-start' : 'justify-end'}`}>
      <div className={`max-w-xs lg:max-w-md ${isBot ? 'order-2' : 'order-1'}`}>
        <div className={`px-4 py-2 rounded-2xl ${isBot ? 'bg-gray-100 text-gray-800' : 'bg-primary-600 text-white'}`}>
          <p className="text-sm whitespace-pre-wrap">{content}</p>

          {insights.length > 0 && (
            <div className="mt-2 pt-2 border-t border-gray-200">
              <p className="text-xs font-medium mb-1">Key Insights:</p>
              {insights.map((insight, index) => (
                <p key={index} className="text-xs opacity-90">• {insight}</p>
              ))}
            </div>
          )}
        </div>

        {suggestions.length > 0 && (
          <div className="mt-3 space-y-2">
            <p className="text-xs font-medium mb-2 opacity-75">Recommended Actions:</p>
            {suggestions.map((suggestion, index) => {
              const suggestionText = typeof suggestion === 'string' ? suggestion : suggestion.title || suggestion.description || '';
              const suggestionClick = suggestionText.includes(':')
                ? suggestionText.split(':')[0].replace(/^\*\*|\*\*$/g, '').trim()
                : suggestionText.replace(/^\*\*|\*\*$/g, '').trim();

              return (
                <button
                  key={index}
                  onClick={() => onSuggestionClick(suggestionClick)}
                  className="block w-full text-left px-3 py-2 text-xs bg-white border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors"
                >
                  {suggestionText}
                </button>
              );
            })}
          </div>
        )}

        {followUpQuestions.length > 0 && (
          <div className="mt-3 space-y-1">
            <p className="text-xs font-medium mb-2 opacity-75">Follow-up Questions:</p>
            {followUpQuestions.map((question, index) => (
              <button
                key={index}
                onClick={() => onSuggestionClick(question)}
                className="block w-full text-left px-3 py-1 text-xs bg-blue-50 border border-blue-200 rounded-lg hover:bg-blue-100 transition-colors text-blue-800"
              >
                {question}
              </button>
            ))}
          </div>
        )}

        <p className="text-xs text-gray-500 mt-1">
          {message.timestamp?.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) || ''}
        </p>
      </div>

      <div className={`flex-shrink-0 ${isBot ? 'order-1 mr-2' : 'order-2 ml-2'}`}>
        <div className={`w-8 h-8 rounded-full flex items-center justify-center ${isBot ? 'bg-gradient-to-r from-purple-500 to-indigo-600' : 'bg-primary-600'}`}>
          {isBot ? <Bot className="w-4 h-4 text-white" /> : <User className="w-4 h-4 text-white" />}
        </div>
      </div>
    </div>
  );
};

// ----------------- VisualizationDisplay -----------------
const VisualizationDisplay = ({ visualization }) => {
  if (!visualization) return null;

  return (
    <div className="space-y-3">
      <p className="text-sm text-gray-600">
        {visualization.title || 'AI-generated financial visualization'}
      </p>
      <FinancialChart visualization={visualization} />
      {visualization.data?.datasets?.[0]?.data && (
        <div className="mt-4 text-center">
          <div className="text-lg font-semibold text-gray-900">
            Total: ${visualization.data.datasets[0].data.reduce((a, b) => a + b, 0).toLocaleString()}
          </div>
          <div className="text-sm text-gray-500">
            {visualization.data.labels?.length || 0} categories
          </div>
        </div>
      )}
    </div>
  );
};

// ----------------- ScoreItem -----------------
const ScoreItem = ({ label, score }) => (
  <div className="flex items-center justify-between">
    <span className="text-sm text-gray-600">{label}</span>
    <div className="flex items-center space-x-2">
      <div className="w-16 bg-gray-200 rounded-full h-2">
        <div
          className={`h-2 rounded-full ${score >= 80 ? 'bg-green-500' : score >= 60 ? 'bg-yellow-500' : 'bg-red-500'}`}
          style={{ width: `${score}%` }}
        />
      </div>
      <span className="text-sm font-medium w-8">{score}</span>
    </div>
  </div>
);

// ----------------- Quick Actions -----------------
const quickActions = [
  { icon: TrendingUp, text: 'Analyze my spending' },
  { icon: Target, text: 'Optimize my goals' },
  { icon: DollarSign, text: 'Investment advice' },
  { icon: PieChart, text: 'Budget recommendations' }
];

// ----------------- Mock Response -----------------
const generateMockResponse = (message, user) => {
  const lowerMessage = message.toLowerCase();
  if (lowerMessage.includes('spend')) {
    return {
      content: `I've analyzed your spending patterns over the past month. You're spending $${Math.round(Math.random() * 1000 + 2000)} monthly.`,
      insights: ['Dining expenses high', 'Transport costs decreased', 'Subscriptions could be optimized'],
      suggestions: ['Set up automatic savings', 'Review subscriptions', 'Meal prep weekends'],
      followUpQuestions: ['What % of income should I save?', 'How to reduce dining expenses?'],
      visualization: { type: 'spending-breakdown', description: 'Monthly spending by category' }
    };
  }
  if (lowerMessage.includes('save')) {
    return {
      content: `Based on your income of $${user?.financialProfile?.monthlyIncome || 4500}, aim to save $${Math.round((user?.financialProfile?.monthlyIncome || 4500) * 0.2)} monthly.`,
      insights: ['Savings rate below 20%', 'Emergency fund should cover 6 months', 'High-yield account increases returns'],
      suggestions: ['Weekly auto transfers', 'Open high-yield savings', 'Optimize subscriptions'],
      followUpQuestions: ['Which high-yield accounts?', 'How much should my emergency fund be?']
    };
  }
  return {
    content: `That's a great question! Let's optimize your budget and savings.`,
    insights: ['Good fundamentals', 'Opportunities for optimization', 'Setting goals helps track progress'],
    suggestions: ['Review budget', 'Analyze spending', 'Set emergency fund goal'],
    followUpQuestions: ['What tools can track spending?', 'How to set realistic goals?']
  };
};

export default Advisor;
